### ISSUE TITLE
Every call create a new instance of the client for search

### ISSUE THREAD

**Issue by vorontsov-pavel** [Cartmaneze/random-post#1]
https://github.com/Cartmaneze/random-post/blob/45bddae3a08276fe0ee55d0624a4eb78df50f3a2/src/secondaryAdapters/googleSearch/imageSearch/api/ImageSearchGoogleAdapter.ts#L11

**Comment by Cartmaneze** [comment]
> https://github.com/Cartmaneze/random-post/blob/45bddae3a08276fe0ee55d0624a4eb78df50f3a2/src/secondaryAdapters/googleSearch/imageSearch/api/ImageSearchGoogleAdapter.ts#L11

fixed
